GuardosEpitech/Guardos

- .github/pull_request_template.md
Add a pr template to assure good code quality. Also, it will increase the understanding why changes are made.
> [SETUP] [ADD] create pr checklist

- packages/backend/src/controllers/userController.ts
- packages/backend/src/index.ts
- packages/backend/src/models/userInterface.ts
- packages/backend/src/routes/login.ts
- packages/backend/src/routes/register.ts
- packages/shared/models/filterInterfaces.ts
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/components/Header/Header.module.scss
- packages/visitorWeb/src/components/Header/Header.tsx
- packages/visitorWeb/src/pages/HomePage/HomePage.tsx
- packages/visitorWeb/src/pages/LoginPage/LoginPage.module.scss
- packages/visitorWeb/src/pages/LoginPage/LoginPage.tsx
- packages/visitorWeb/src/pages/LoginPage/index.ts
- packages/visitorWeb/src/pages/RegistrationPage/RegistrationPage.module.scss
- packages/visitorWeb/src/pages/RegistrationPage/RegistrationPage.tsx
- packages/visitorWeb/src/pages/RegistrationPage/index.ts
- packages/visitorWeb/src/router/Router.tsx
Adding Routes for registering and loggin in
> [BE] [ADD] Filter/Register/Login Routes

- packages/visitorWeb/cypress/e2e/BackendFilter/filter.cy.ts
Addes cypress tests
We want to keep track of the filter logic, to ensure it will not be broken after changes. For this we need a working testing suit.
5. Run tests
> [BE][ADD] add cypress filter tests

- .github/workflows/ci_be.yml
- .github/workflows/ci_fe.yml
- packages/backend/package.json
- packages/visitorWeb/package.json
> [DEVOPS] [ADD] Github Actions

- documentation/backend/codingstyle/README.md
- documentation/frontend/codingstyle/README.md
Added codingstyle documentation for our frontend/backend languages
> [SETUP] [ADD] EIP-152 codingstyle documentation

- packages/restoWeb/src/components/dumpComponents/popup/Popup.module.scss
- packages/restoWeb/src/components/dumpComponents/popup/Popup.tsx
Added outline for popup component.
Changed popup style to make it better visible.
5. Run tests
> [FE] [MODIFY] delete dish popup

- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
Verify value for mandatory fields.
When editing dishes, we need to make sure that some values are set. This change makes sure that name, price (required: positive float), category and restaurant is set.
5. Run tests
> [FE] [MODIFY] edit dish page

- packages/restoWeb/src/pages/DishesPage/DishesPage.module.scss
- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
Added error message if no dishes registered for Restaurant.
This change prevents an empty screen if there are no dishes to display.
This way, the user wont be confused and is suggested to add the first dish.
5. Run tests
> [FE] [ADD] add dishes overview page

- packages/restoWeb/.env
- packages/visitorWeb/.env
Add server adresse instead of localhost
5. Run tests
> [BE] [FIX] change url to server address

- packages/restoWeb/src/components/dumpComponents/popup/Popup.tsx
> [FE][MODIFY] Popup component styles twices

- packages/backend/cypress/e2e/products.cy.ts
- packages/backend/cypress/e2e/restoTests.cy.ts
- packages/backend/cypress/plugins/index.js
- packages/backend/cypress/support/e2e.ts
- packages/backend/package.json
- packages/restoWeb/cypress/e2e/DishesPageTest/DishesPageTest.cy.ts
- packages/restoWeb/cypress/e2e/HomePageTest/HomePageTest.cy.ts
- packages/restoWeb/cypress/e2e/ProductPageTest/ProductPageTest.cy.ts
- packages/restoWeb/package.json
Complete tests for FE RestoWeb Resto, Dishes, Products as well as BE Products and Resto
Now most of the frontend functions of the restaurant website are tested
5. Run tests
> [FE/BE] [ADD] Eip 195 FE tests for Resto Dishes Products of Restaurant Web

- packages/backend/src/index.ts
- packages/backend/src/models/imageInterfaces.ts
- packages/backend/src/routes/images.ts
Added API Routes and proper default templates for the later development.
We want to have certain routes for storing images in our db, so we need Routes
> [BE] [ADD] API Routes for images (EIP-214)

- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
> [FE] [FIX] fix error with allergens not saving

- packages/backend/src/index.ts
- packages/backend/src/routes/logout.ts
Added logout and modified login
> [BE] [ADD] Logout for RestoWeb

- packages/visitorWeb/src/components/Map/Map.module.scss
- packages/visitorWeb/src/pages/AboutUsPage/AboutUsPage.module.scss
- packages/visitorWeb/src/pages/AboutUsPage/AboutUsPage.tsx
- packages/visitorWeb/src/pages/AppOutlet/AppOutlet.module.scss
- packages/visitorWeb/src/pages/AppOutlet/AppOutlet.tsx
- packages/visitorWeb/src/pages/AppOutlet/index.ts
- packages/visitorWeb/src/pages/ContactPage/ContactPage.module.scss
- packages/visitorWeb/src/pages/ContactPage/ContactPage.tsx
- packages/visitorWeb/src/pages/HomePage/HomePage.tsx
- packages/visitorWeb/src/pages/LoginPage/LoginPage.tsx
- packages/visitorWeb/src/pages/MapPage/MapPage.module.scss
- packages/visitorWeb/src/pages/MapPage/MapPage.tsx
- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
- packages/visitorWeb/src/pages/RegistrationPage/RegistrationPage.tsx
- packages/visitorWeb/src/router/Router.tsx
adjust element to have same header and footer on all pages
unify footer
5. Run tests
> [FE] [MODIFY] unify footer for visitor web

- packages/restoWeb/src/pages/AddDishPage/AddDishPage.tsx
- packages/restoWeb/src/pages/AddProductPage/AddProductPage.tsx
- packages/restoWeb/src/pages/AddRestaurantPage/AddRestaurantPage.tsx
- packages/restoWeb/src/pages/AppOutlet/AppOutlet.module.scss
- packages/restoWeb/src/pages/AppOutlet/AppOutlet.tsx
- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
- packages/restoWeb/src/pages/EditDishPage/EditDishPage.tsx
- packages/restoWeb/src/pages/EditProductPage/EditProductPage.tsx
- packages/restoWeb/src/pages/EditRestaurantPage/EditRestaurantPage.tsx
- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
- packages/restoWeb/src/pages/ProductsPage/ProductsPage.tsx
adjust element to have same header and footer on all pages
unify footer
5. Run tests
> [FE] [MODIFY] unify footer for resto web

- packages/backend/src/controllers/userRestoController.ts
>  [BE] [ADD] Logout for Restousers

- package.json
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/controllers/restaurantFilterController.ts
- packages/backend/src/controllers/userRestoController.ts
- packages/backend/src/middleware/filterMiddleWare.ts
- packages/backend/src/models/restaurantInterfaces.ts
- packages/backend/src/models/userRestaurantInterfaces.ts
- packages/backend/src/routes/login.ts
- packages/backend/src/routes/restaurants.ts
- packages/restoWeb/src/components/dumpComponents/Header/Header.module.scss
- packages/restoWeb/src/components/dumpComponents/Header/Header.tsx
- packages/restoWeb/src/components/dumpComponents/buttons/FixedBtn/FixedBtn.module.scss
- packages/restoWeb/src/pages/HomePage/HomePage.module.scss
- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/restoWeb/src/pages/LoginPage/LoginPage.module.scss
- packages/restoWeb/src/pages/LoginPage/LoginPage.tsx
- packages/restoWeb/src/pages/LoginPage/index.ts
- packages/restoWeb/src/pages/RegistrationPage/RegistrationPage.module.scss
- packages/restoWeb/src/pages/RegistrationPage/RegistrationPage.tsx
- packages/restoWeb/src/pages/RegistrationPage/index.ts
- packages/restoWeb/src/router/Router.tsx
- packages/restoWeb/src/services/restoCalls.ts
- packages/restoWeb/src/services/userCalls.ts
- packages/shared/models/restaurantInterfaces.ts
We can now see a clear behavior for the user of the Resto web. The Restaurants will not be shown for other users
> [BE] [ADD] added Logic for user login in restoweb

- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/productsController.ts
- packages/backend/src/controllers/userController.ts
- packages/backend/src/models/productsInterfaces.ts
- packages/backend/src/models/userInterface.ts
- packages/backend/src/routes/dishes.ts
- packages/backend/src/routes/login.ts
- packages/backend/src/routes/products.ts
- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
- packages/restoWeb/src/pages/AddDishPage/AddDishPage.module.scss
- packages/restoWeb/src/pages/AddProductPage/AddProductPage.module.scss
- packages/restoWeb/src/pages/AddRestaurantPage/AddRestaurantPage.module.scss
- packages/restoWeb/src/pages/DishesPage/DishesPage.module.scss
- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
- packages/restoWeb/src/pages/EditDishPage/EditDishPage.module.scss
- packages/restoWeb/src/pages/EditProductPage/EditProductPage.module.scss
- packages/restoWeb/src/pages/EditRestaurantPage/EditRestaurantPage.module.scss
- packages/restoWeb/src/pages/MenuPage/MenuPage.module.scss
- packages/restoWeb/src/pages/ProductsPage/ProductsPage.module.scss
- packages/restoWeb/src/pages/ProductsPage/ProductsPage.tsx
- packages/restoWeb/src/services/dishCalls.ts
- packages/restoWeb/src/services/productCalls.ts
- packages/shared/models/productInterfaces.ts
Filter the shown products and dishes filtered by the logged in user.
5. Run tests
> [BE] [ADD] Filter by resto user

- packages/visitorWeb/src/components/Header/Header.module.scss
- packages/visitorWeb/src/components/Header/Header.tsx
- packages/visitorWeb/src/pages/AboutUsPage/AboutUsPage.module.scss
- packages/visitorWeb/src/pages/AboutUsPage/AboutUsPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/index.ts
- packages/visitorWeb/src/router/Router.tsx
Added a My Account Page that will be visible if you are logged in
> [FE] [ADD] My Account Page

- packages/backend/src/controllers/dishesController.ts
Improve error handling for empty objects.
5. Run tests
> [BE] [MODIFY] add error handling dishes by user

- packages/backend/.env.default
- packages/restoWeb/webpack.config.js
- packages/visitorWeb/webpack.config.js
added host to webpackes
We now have the domain www.guardos.eu 
To use this we have to change the  webpakcges
5. Run tests
> [FE] [FIX] add hosts to webpack.config.js

- packages/visitorWeb/package.json
- packages/visitorWeb/src/components/Slider/TeamSlider.module.scss
- packages/visitorWeb/src/components/Slider/TeamSlider.tsx
- packages/visitorWeb/src/pages/IntroPage/IntroPage.module.scss
- packages/visitorWeb/src/pages/IntroPage/IntroPage.tsx
- packages/visitorWeb/src/pages/IntroPage/timeline.min.css
Had some open Content to add for the FU. Landing Page is now completed
> [FE] [MODIFY] Added content for the FU

- .gitignore
- packages/restoWeb/cypress.config.ts
- packages/restoWeb/cypress/e2e/RestaurantTest/RestaurantTest.cy.ts
- packages/restoWeb/src/components/RestoCard/RestoCard.tsx
- packages/restoWeb/src/components/menu/Dish/DishActions/DishActions.tsx
- packages/visitorWeb/cypress.config.ts
Frontend Tests for Restaurant + modified cypress config + Fix for the Restaurant delete button
> [FE] [ADD] Frontend Tests for Restaurant and modified cypress config

- packages/backend/cypress/e2e/email.cy.ts
- packages/backend/src/controllers/userController.ts
- packages/backend/src/controllers/userRestoController.ts
- packages/backend/src/routes/email.ts
- packages/backend/src/routes/login.ts
- packages/backend/src/routes/restoProfile.ts
- packages/backend/src/routes/visitorProfile.ts
- packages/restoWeb/src/pages/ChangePasswordPage/ChangePasswordPage.module.scss
- packages/restoWeb/src/pages/ChangePasswordPage/ChangePasswordPage.tsx
- packages/restoWeb/src/pages/ChangePasswordPage/index.ts
- packages/restoWeb/src/pages/ResetPasswordPage/ResetPassword.module.scss
- packages/restoWeb/src/pages/ResetPasswordPage/ResetPassword.tsx
- packages/restoWeb/src/router/Router.tsx
- packages/restoWeb/src/services/userCalls.ts
- packages/visitorWeb/src/pages/ChangePasswordPage/ChangePasswordPage.module.scss
- packages/visitorWeb/src/pages/ChangePasswordPage/ChangePasswordPage.tsx
- packages/visitorWeb/src/pages/ChangePasswordPage/index.ts
- packages/visitorWeb/src/pages/ResetPasswordPage/ResetPassword.tsx
- packages/visitorWeb/src/router/Router.tsx
- packages/visitorWeb/src/services/userCalls.ts
new constants needs to be added in the backend .env file:
USER_SITE="http://localhost:8082"
RESTO_SITE="http://localhost:8080"
Changes are all regarding the implementation for forgetting the password, in that the ticket enables the user to send an email with a timetoken + usertoken to then recover / change the password for the account.
> [BE] [ADD] Forgot Password

- packages/backend/cypress/e2e/favourites.cy.ts
- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/favouritesController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/controllers/restaurantFilterController.ts
- packages/backend/src/index.ts
- packages/backend/src/middleware/dishesMiddelWare.ts
- packages/backend/src/middleware/filterMiddleWare.ts
- packages/backend/src/models/communicationInterfaces.ts
- packages/backend/src/models/dishInterfaces.ts
- packages/backend/src/models/restaurantInterfaces.ts
- packages/backend/src/models/userInterface.ts
- packages/backend/src/routes/favourites.ts
- packages/backend/src/routes/products.ts
- packages/backend/src/routes/restaurants.ts
- packages/restoWeb/src/components/RestoCard/RestoCard.tsx
- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
- packages/restoWeb/src/pages/AddDishPage/AddDishPage.tsx
- packages/restoWeb/src/pages/EditDishPage/EditDishPage.tsx
- packages/restoWeb/src/pages/EditProductPage/EditProductPage.tsx
- packages/shared/models/communicationInterfaces.ts
- packages/shared/models/dishInterfaces.ts
- packages/shared/models/restaurantInterfaces.ts
- packages/visitorWeb/src/components/Map/Map.tsx
Let the visitor save restaurants and dishes in a favourite list to easier find them. Add routes to add, get and delete objects from the list (saved in user profile). identification via uid in objects
E2E cypress tests to check all routes (add, delete, get resto/dish favourites)
5. Run tests
> [BE] [ADD] Favourite lists restos and dishes for visitor

- packages/backend/cypress/e2e/payment.cy.ts
- packages/backend/package.json
- packages/backend/src/index.ts
- packages/backend/src/routes/payments.ts
- packages/visitorWeb/src/pages/Payments/Accept/PaymentSuccessPage.module.scss
- packages/visitorWeb/src/pages/Payments/Accept/PaymentSuccessPage.tsx
- packages/visitorWeb/src/pages/Payments/Accept/index.ts
- packages/visitorWeb/src/pages/Payments/Failed/PaymentFailedContainer.module.scss
- packages/visitorWeb/src/pages/Payments/Failed/PaymentFailedPage.tsx
- packages/visitorWeb/src/pages/Payments/Failed/index.ts
- packages/visitorWeb/src/router/Router.tsx
At some point we want to make money. 
To do this, we need a way to collect money.
also added simple page for showing success and failed status.
Added stripe connectivity.
You need to add the following two lines to the .env in the backend:
STRIPE_SECRET_KEY=""
FREE_PAYMENT=""
(For these values: https://epitech-eip.atlassian.net/wiki/spaces/EIP/pages/10452993/DataBase+Access+.env+file)
5. Run tests
> [BE] [ADD] add stripe connectivity 

- packages/backend/src/routes/dishes.ts
- packages/backend/src/routes/foodCategories.ts
- packages/backend/src/routes/ingredients.ts
- packages/backend/src/routes/products.ts
- packages/backend/src/routes/restaurants.ts
Add try catch statement to all BE routes to prevent server from crashing.
5. Run tests
> [BE] [MODIFY] add try catch for all routes

- packages/backend/src/index.ts
- packages/backend/src/routes/featureRequest.ts
- packages/restoWeb/cypress/e2e/FeatureRequest/featureRequest.cy.ts
- packages/restoWeb/src/pages/FeatureRequest/FeatureRequest.module.scss
- packages/restoWeb/src/pages/FeatureRequest/FeatureRequest.tsx
- packages/restoWeb/src/pages/FeatureRequest/index.ts
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/restoWeb/src/router/Router.tsx
- packages/visitorWeb/cypress/e2e/FeatureRequest/featureRequest.cy.ts
- packages/visitorWeb/src/pages/FeatureRequest/FeatureRequest.module.scss
- packages/visitorWeb/src/pages/FeatureRequest/FeatureRequest.tsx
- packages/visitorWeb/src/pages/FeatureRequest/index.ts
- packages/visitorWeb/src/pages/IntroPage/IntroPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/router/Router.tsx
Addition of the features request for both of the Web.
Allowing user to send email to us if they have any request.
5. Run tests
> BE/FE Feature Request for both Web

- packages/backend/cypress/e2e/menu.cy.ts
- packages/backend/src/controllers/menuController.ts
- packages/backend/src/index.ts
- packages/backend/src/routes/menu.ts
- packages/shared/models/dishInterfaces.ts
Filter the restaurants menu by allergen preferences, based on the current search. This method will return all dishes grouped by the categories / mealTypes. However, it adds a "fitsPreference" boolean to each dish to determine which will be good for the visitor.
Cypress tests to check on
- no allergens set
- allergen set that will set some dishes to fitsPreference = true
5. Run tests
> [BE] [ADD] filter menu by preference

- packages/backend/src/controllers/menuDesignsController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/controllers/restaurantFilterController.ts
- packages/backend/src/index.ts
- packages/backend/src/middleware/filterMiddleWare.ts
- packages/backend/src/models/communicationInterfaces.ts
- packages/backend/src/models/menuDesignInterfaces.ts
- packages/backend/src/models/restaurantInterfaces.ts
- packages/backend/src/routes/menuDesigns.ts
- packages/backend/src/routes/restaurants.ts
- packages/restoWeb/src/components/RestoCard/RestoCard.tsx
- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
- packages/restoWeb/src/pages/EditRestaurantPage/EditRestaurantPage.tsx
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
- packages/restoWeb/src/services/restoCalls.ts
- packages/shared/models/menuDesignsInterfaces.ts
- packages/shared/models/restaurantInterfaces.ts
Added functionalities about adding the menu designs FE and BE. Made also some fixes for the restocards
> [BE] [ADD] All functionalities for menu design

- packages/backend/cypress/e2e/filter.cy.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/middleware/newFilterMiddleware.ts
- packages/backend/src/models/locationInterfaces.ts
- packages/backend/src/models/restaurantInterfaces.ts
- packages/backend/src/routes/filter.ts
- packages/visitorWeb/cypress/e2e/HomePageTest/HomePageTest.cy.ts
- packages/visitorWeb/src/components/Filter/Filter.module.scss
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/components/Map/Map.module.scss
- packages/visitorWeb/src/components/Map/Map.tsx
- packages/visitorWeb/src/components/RestoCard/RestoCard.module.scss
- packages/visitorWeb/src/components/RestoCard/RestoCard.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.module.scss
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
- packages/visitorWeb/src/pages/RestoPage/index.tsx
- packages/visitorWeb/src/router/Router.tsx
- packages/visitorWeb/src/services/filterCalls.ts
This PR combines the filter for List and Map view and implements a new filter for the backend
5. Run tests
> [FE] [MODIFY] Eip 238 visitor filter list–map

- packages/backend/src/middleware/newFilterMiddleware.ts
This will fix an issue with the filter in the backend that resulted in an error 
5. Run tests
> [BE] [FIX] HOTFIX for filter backend

- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
Fix adding favs to correct homepage for visitor web (was using HomePage - that we dont use anymore - instead of RestoScreen)
5. Run tests
> [FE] [FIX] add fav to correct homepage

- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/index.ts
- packages/backend/src/routes/register.ts
- packages/backend/src/routes/restoFilter.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/restoWeb/src/services/restoCalls.ts
added route for filtering restaurants by name / location
User should be able to filter for his restaurants by name or location
Tests coming soon
5. Run tests
> [BE] [ADD] add route for filter restaurants + added searchbar in FE

- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
Fix change and delete resto img translation.
5. Run tests
> [FE] [FIX] edit resto img translation link

- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
> [FE] [MODIFY] Menu navigation fix

- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/visitorWeb/src/pages/HomePage/HomePage.tsx
- packages/visitorWeb/src/pages/LoginPage/LoginPage.tsx
This removes the errors in the home page and Login page for the visitor and an error in the home page for the resto
5. Run tests
> [FE] [FIX] fix errors visitor home & login page and resto homepage

- packages/restoWeb/i18n/de.json
- packages/restoWeb/src/pages/HomePage/HomePage.module.scss
- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/restoWeb/src/pages/LoginPage/LoginPage.tsx
Remove thrid party login buttons
change naming from default german string in filter
resize filter menu
5. Run tests
> [FE] [FIX] rename filter 

- packages/backend/src/controllers/userController.ts
- packages/backend/src/controllers/userRestoController.ts
put all decryped in a try block 
hopefully ensure that the backend will not crash randomly if a token can't be read..
not working backend is not a good backend :/
> [BE] [FIX] catch all decrypts to ensure the backend will not crash

- packages/restoWeb/src/components/dumpComponents/popup/Popup.tsx
- packages/restoWeb/src/pages/HomePage/HomePage.tsx
Fixes the resto popup
5. Run tests
> [FE] [FIX] resto popup

- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/SubscriptionBox/SubscriptionBox.module.scss
- packages/restoWeb/src/components/SubscriptionBox/SubscriptionBox.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/restoWeb/src/pages/SubscriptionPage/SubscriptionPage.module.scss
- packages/restoWeb/src/pages/SubscriptionPage/SubscriptionPage.tsx
- packages/restoWeb/src/router/Router.tsx
- packages/restoWeb/src/services/permissionsCalls.ts
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/SubscriptionBox/SubscriptionBox.module.scss
- packages/visitorWeb/src/components/SubscriptionBox/SubscriptionBox.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/pages/SubscriptionPage/SubscriptionPage.module.scss
- packages/visitorWeb/src/pages/SubscriptionPage/SubscriptionPage.tsx
- packages/visitorWeb/src/router/Router.tsx
- packages/visitorWeb/src/services/permissionsCalls.ts
Allow the user to manage his subscription and see the benefits of each as well as which one is active.
5. Run tests
> [FE] [ADD] user permission system

- packages/restoWeb/package.json
- packages/restoWeb/src/components/dumpComponents/Header/Header.module.scss
- packages/restoWeb/src/components/dumpComponents/Header/Header.tsx
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/package.json
- packages/visitorWeb/src/components/Header/Header.module.scss
- packages/visitorWeb/src/components/Header/Header.tsx
Addition of the hamburger navigation for visitor & resto Web
So it's easyer to navigate on both website 
5. Run tests
> [FE] [ADD] Hamburger navigation for visitor & resto Web

- packages/backend/src/controllers/userRestoController.ts
Add error output to fix resto app profile management.
5. Run tests
> [BE] [FIX] add error output

- packages/restoWeb/src/components/CookieBanner/CookieBanner.tsx
- packages/visitorWeb/src/components/CookieBanner/CookieBanner.tsx
fixes an error when translated to german or english
5. Run tests
> [FE] [MODIFY] fixed error when translated

- packages/backend/src/index.ts
- packages/backend/src/routes/restaurants.ts
- packages/restoWeb/src/components/RestoCard/RestoCard.module.scss
- packages/restoWeb/src/components/RestoCard/RestoCard.tsx
- packages/restoWeb/src/components/dumpComponents/Header/Header.module.scss
- packages/restoWeb/src/services/callImages.ts
- packages/restoWeb/src/services/dishCalls.ts
- packages/restoWeb/src/services/ingredientsCalls.ts
- packages/restoWeb/src/services/permissionsCalls.ts
- packages/restoWeb/src/services/productCalls.ts
- packages/restoWeb/src/services/profileCalls.ts
- packages/restoWeb/src/services/restoCalls.ts
- packages/restoWeb/src/services/userCalls.ts
- packages/visitorWeb/src/components/RestoCard/RestoCard.module.scss
- packages/visitorWeb/src/components/RestoDetailOverlay/RestoDetailOverlay.module.scss
- packages/visitorWeb/src/components/menu/Dish/Dish.module.scss
- packages/visitorWeb/src/services/imageCalls.ts
- packages/visitorWeb/src/services/menuCalls.ts
- packages/visitorWeb/src/services/permissionsCalls.ts
- packages/visitorWeb/src/services/profileCalls.ts
- packages/visitorWeb/src/services/userCalls.ts
> [FE] [MODIFY] Backend Calls and Error Throws

- packages/restoWeb/src/components/RestoCard/RestoCard.module.scss
- packages/visitorWeb/src/components/RestoCard/RestoCard.module.scss
> [FE] [MODIFY] CSS

- packages/backend/cypress/e2e/filter.cy.ts
- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/middleware/newFilterMiddleware.ts
- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
- packages/visitorWeb/src/components/InputSearch/InputSearch.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
This PR modified the filter, add added categories to dish creation (if resto is selected) and fixes an issue with the input search 
5. Run tests
> [BE] [MODIFY] Improve filter and categories

- packages/visitorWeb/src/components/RestoDetailOverlay/RestoDetailOverlay.module.scss
- packages/visitorWeb/src/pages/IntroPage/IntroPage.tsx
Changes to the intropage and css styling
> [FE] [MODIFY] Fix Delivery

- packages/backend/src/routes/featureRequest.ts
- packages/restoWeb/src/pages/FeatureRequest/FeatureRequest.tsx
- packages/visitorWeb/src/pages/FeatureRequest/FeatureRequest.tsx
This modifies the feature request, now if a premium user sends a feature request the email will be marked as 'High priority' in our inbox.
5. Run tests
> [BE] [ADD] add priority to feature request premium

- packages/backend/cypress/e2e/dishDiscount.cy.ts
- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/controllers/restaurantFilterController.ts
- packages/backend/src/middleware/newFilterMiddleware.ts
- packages/backend/src/models/communicationInterfaces.ts
- packages/backend/src/models/restaurantInterfaces.ts
- packages/backend/src/routes/dishes.ts
- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
- packages/shared/models/dishInterfaces.ts
Adds the backend to add or remove the discount from a dish
cypress test
5. Run tests
> [BE] [ADD] Eip 288 be manage dish discount

- packages/backend/src/controllers/dishesController.ts
- packages/restoWeb/src/pages/UserSupport/UserSupportPage.tsx
fixes the user support page for resto web and removes a double import in the be
5. Run tests
> [FE] [FIX] fix userSupport page resto

- packages/backend/src/routes/visitorProfile.ts
Limit saved filters based on subscription model. 
5. Run tests
> [BE] [MODIFY] limit saved filters

- packages/backend/src/routes/visitorProfile.ts
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/Filter/Filter.module.scss
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/SubscriptionPage/SubscriptionPage.tsx
- packages/visitorWeb/src/services/profileCalls.ts
Limit the amount of saved filters based on the users subscription. For now, have:
- 1 filter for "default" subscription
- 2 filter for "basicSubscription"
- 3 filter for "premiumUser" 
Also, the subscriptionPage shows the rule for filter limitations.
5. Run tests
> [FE] [ADD] limit amount of saved filters

- packages/backend/cypress/e2e/comboDish.cy.ts
- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/controllers/restaurantFilterController.ts
- packages/backend/src/middleware/newFilterMiddleware.ts
- packages/backend/src/models/restaurantInterfaces.ts
- packages/backend/src/routes/dishes.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/package.json
- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
- packages/restoWeb/src/components/menu/Dish/Dish.module.scss
- packages/restoWeb/src/components/menu/Dish/Dish.tsx
- packages/restoWeb/src/components/menu/Dish/DishActions/DishActions.tsx
- packages/restoWeb/src/pages/DiscountDishPage/DiscountDishPage.module.scss
- packages/restoWeb/src/pages/DiscountDishPage/DiscountDishPage.tsx
- packages/restoWeb/src/pages/DiscountDishPage/index.ts
- packages/restoWeb/src/pages/EditDishPage/EditDishPage.tsx
- packages/restoWeb/src/router/Router.tsx
- packages/restoWeb/src/services/dishCalls.ts
- packages/shared/models/dishInterfaces.ts
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/menu/Dish/Dish.module.scss
- packages/visitorWeb/src/components/menu/Dish/Dish.tsx
- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
adds a screen for resto to add discounts to dishes and make it visible on the dish card for resto and visitor
5. Run tests
> [FE] [ADD] Eip 237 fe manage dish discount

- docker-compose.yaml
- packages/restoWeb/webpack.config.js
- prometheus.yml
> [DEVOPS] [MERGE] add monitoring for server 

- packages/backend/src/routes/dishes.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/menu/Dish/Dish.tsx
- packages/restoWeb/src/pages/DishComboPage/DishComboPage.module.scss
- packages/restoWeb/src/pages/DishComboPage/DishComboPage.tsx
- packages/restoWeb/src/pages/DishComboPage/index.ts
- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
- packages/restoWeb/src/router/Router.tsx
- packages/restoWeb/src/services/dishCalls.ts
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/menu/Dish/Dish.tsx
- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/services/menuCalls.ts
With this the resto user can add recommendations on dish combinations and the user can view them
5. Run tests
> [FE] [ADD] Eip 326 fe add dish combo

- packages/backend/src/controllers/emailController.ts
- packages/backend/src/controllers/userRestoController.ts
- packages/backend/src/middleware/twoFactorMiddleware.ts
- packages/backend/src/models/communicationInterfaces.ts
- packages/backend/src/models/userRestaurantInterfaces.ts
- packages/backend/src/routes/login.ts
- packages/backend/src/routes/restoProfile.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/TwoFactorAuth/TwoFactorAuthentification.tsx
- packages/restoWeb/src/pages/LoginPage/LoginPage.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/restoWeb/src/services/profileCalls.ts
- packages/restoWeb/src/services/userCalls.ts
Add two factor login for restaurant user
Added two factor login for restaurant user to improve security 
5. Run tests
> [BE/FE] add possibility to use two factor authentification for restaurant user

- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/Accordion/Accordion.module.scss
- packages/restoWeb/src/components/Accordion/Accordion.tsx
- packages/restoWeb/src/components/dumpComponents/Header/Header.tsx
- packages/restoWeb/src/pages/GuidesPage/GuidesPage.module.scss
- packages/restoWeb/src/pages/GuidesPage/GuidesPage.tsx
- packages/restoWeb/src/pages/GuidesPage/index.ts
- packages/restoWeb/src/router/Router.tsx
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/Header/Header.tsx
- packages/visitorWeb/src/pages/GuidesPage/GuidesPage.module.scss
- packages/visitorWeb/src/pages/GuidesPage/GuidesPage.tsx
- packages/visitorWeb/src/pages/GuidesPage/index.ts
- packages/visitorWeb/src/router/Router.tsx
Add guide page to inform resto and visitors about allergens and how to prevent them.
5. Run tests
> [FE] [ADD] guide pages for resto and visitor

- packages/backend/src/controllers/statisticsController.ts
> [BE] [FIX] fixes an issue when disliked ingredients are undefined

- packages/backend/src/controllers/userController.ts
- packages/backend/src/controllers/userRestoController.ts
- packages/backend/src/models/userInterface.ts
- packages/backend/src/models/userRestaurantInterfaces.ts
- packages/backend/src/routes/payments.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/pages/SubscriptionPage/SubscriptionPage.module.scss
- packages/restoWeb/src/pages/SubscriptionPage/SubscriptionPage.tsx
- packages/restoWeb/src/services/userCalls.ts
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/pages/SubscriptionPage/SubscriptionPage.module.scss
- packages/visitorWeb/src/pages/SubscriptionPage/SubscriptionPage.tsx
- packages/visitorWeb/src/services/userCalls.ts
> [FE] [ADD] Subscription Connection

- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
> [FE] [FIX] dishCard

- packages/backend/src/controllers/restaurantController.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/pages/AddCategoryPage/AddCategoryPage.tsx
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
- packages/shared/models/categoryInterfaces.ts
> [FE] [MODIFY] edit and delete categories

- packages/backend/src/routes/deleteUsers.ts
- packages/backend/src/routes/login.ts
- packages/restoWeb/src/components/dumpComponents/Header/Header.module.scss
- packages/restoWeb/src/components/dumpComponents/Header/Header.tsx
- packages/restoWeb/src/pages/AddCategoryPage/AddCategoryPage.tsx
- packages/restoWeb/src/pages/LoginPage/LoginPage.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/Header/Header.module.scss
- packages/visitorWeb/src/components/InputSearch/InputSearch.module.scss
- packages/visitorWeb/src/components/InputSearchAutocomplete/AutoComplete.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.module.scss
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
> [FE] [MODIFY] bugfixing

- packages/backend/src/routes/login.ts
> [BE] [FIX] fix login when 2fa false

- packages/restoWeb/src/components/dumpComponents/Header/Header.tsx
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/Header/Header.tsx
- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
> [FE] [FIX] fix vistor and resto bugs

- packages/backend/src/controllers/mapController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/middleware/newFilterMiddleware.ts
- packages/backend/src/models/communicationInterfaces.ts
- packages/shared/models/communicationInterfaces.ts
- packages/shared/models/locationInterfaces.ts
- packages/visitorWeb/src/components/AddressInput/AddressInput.module.scss
- packages/visitorWeb/src/components/AddressInput/AddressInput.tsx
- packages/visitorWeb/src/components/InputSearch/InputSearch.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.module.scss
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
> [FE/BE] [FIX] Fix filter location and distance

- packages/backend/src/controllers/restaurantController.ts
> [BE] [FIX] fix edit resto

- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/Map/Map.tsx
> [FE] [FIX] fix translation

- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/pages/RatingPage/RatingPage.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
> 6 error alban

- packages/backend/src/controllers/userController.ts
- packages/backend/src/controllers/userRestoController.ts
- packages/backend/src/routes/restoProfile.ts
- packages/backend/src/routes/visitorProfile.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/restoWeb/src/services/profileCalls.ts
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/services/profileCalls.ts
Add a check when editing profile data: username and email need to be unique. If one of them is used by another user, saving the changes will fail.
5. Run tests
> [FE] [FIX] add check if username and email already exist

- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/pages/MenuPage/MenuPage.module.scss
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
filter menu for resto web, so no empty categories are displayed. Also add message if no menu is available yet.
5. Run tests
> [FE] [ADD] filter out empty categories and print no-menu-msg

- packages/visitorWeb/src/pages/LoginPage/LoginPage.tsx
> [FE] [FIX] log in error visitor

- packages/restoWeb/src/pages/AppOutlet/AppOutlet.tsx
- packages/shared/pages/ImprintPage/ImprintPage.tsx
- packages/shared/pages/PrivacyPage/PrivacyPage.tsx
- packages/visitorWeb/src/pages/AppOutlet/AppOutlet.tsx
- packages/visitorWeb/src/pages/ContactPage/ContactPage.tsx
removed all mentions. of our telephone number (visitor and resto)
5. Run tests
> [FE] [REMOVE] removed fake telephone from web

- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
Make sure allergen list is the same in profile and filter for consistent experience and mapping.
5. Run tests
> [FE] [FIX] sync allergens in profile and filter

- packages/visitorWeb/src/components/Filter/Filter.tsx
Previous bug: default allergens (fetched from profile allergens) were not passed down to the menu.
5. Run tests
> [FE] [FIX] pass down default allergens to menu

- packages/backend/src/models/communicationInterfaces.ts
- packages/backend/src/models/userInterface.ts
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
Group filters are now included for saved filters.
5. Run tests
> [FE] [FIX] save group profiles in saved filter

- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
Fix Issue with vlayout not closed from the previous merge regarding share option
5. Run tests
> [FE][FIX] Fix issue from previous merge

- packages/backend/src/controllers/mapController.ts
- packages/backend/src/controllers/productsController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/routes/products.ts
- packages/backend/src/routes/restaurants.ts
- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
- packages/restoWeb/src/pages/DiscountDishPage/DiscountDishPage.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/restoWeb/src/pages/Payments/PaymentsPage/PaymentPage.tsx
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/Filter/Filter.module.scss
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
> [BE] [ADD] Payment/Forms/Subscription BugFixes

- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/pages/AddCategoryPage/AddCategoryPage.tsx
one message if there are no restaurants available and one message if there are no categories for a restaurant 
5. Run tests
> [FE] [MODIFY] adjusted error messages for categories screen

- packages/visitorWeb/src/components/Filter/Filter.tsx
> [FE] [FIX] empty object check

- packages/backend/package.json
- packages/backend/src/routes/featureRequest.ts
- packages/backend/src/routes/userSupport.ts
Fix mail issue now using SendGrid as provider 
5. Run tests
> [BE][FIX] Fix mail services

- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/dumpComponents/SuccessAlert/SuccessAlert.tsx
- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/restoWeb/src/pages/ProductsPage/ProductsPage.tsx
Better Success Messages for the User in every form
> [FE] [ADD] Better Success Messages for the User

- packages/backend/src/controllers/emailController.ts
- packages/backend/src/controllers/userController.ts
- packages/backend/src/controllers/userRestoController.ts
- packages/backend/src/models/userInterface.ts
- packages/backend/src/models/userRestaurantInterfaces.ts
- packages/backend/src/routes/email.ts
- packages/backend/src/routes/login.ts
- packages/backend/src/routes/register.ts
- packages/backend/src/routes/restoProfile.ts
- packages/backend/src/routes/visitorProfile.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/pages/LoginPage/LoginPage.module.scss
- packages/restoWeb/src/pages/LoginPage/LoginPage.tsx
- packages/restoWeb/src/pages/RegistrationPage/VerifyEmailPage/VerifyEmailPage.module.scss
- packages/restoWeb/src/pages/RegistrationPage/VerifyEmailPage/VerifyEmailPage.tsx
- packages/restoWeb/src/pages/RegistrationPage/VerifyEmailPage/index.ts
- packages/restoWeb/src/router/Router.tsx
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/pages/LoginPage/LoginPage.module.scss
- packages/visitorWeb/src/pages/LoginPage/LoginPage.tsx
- packages/visitorWeb/src/pages/RegistrationPage/VerifyEmailPage/VerifyEmailPage.module.scss
- packages/visitorWeb/src/pages/RegistrationPage/VerifyEmailPage/VerifyEmailPage.tsx
- packages/visitorWeb/src/pages/RegistrationPage/VerifyEmailPage/index.ts
- packages/visitorWeb/src/router/Router.tsx
this adds verify email when registering and changing email (on next login) also fixes forgot password, and two factor auth to send emails again
please add this to the backend env:
SENDGRID_API_KEY=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
SUPPORT=guardos-help2@outlook.com
REQUEST=guardos-help3@outlook.com
JWT_SECRET=EpitechIsGreat
5. Run tests
- all …
> [BE/FE] [ADD] adds verify email

- packages/backend/src/controllers/allergenDetectionController.ts
- packages/backend/src/controllers/mapController.ts
- packages/backend/src/controllers/productsController.ts
- packages/backend/src/routes/dishes.ts
- packages/backend/src/routes/ingredients.ts
- packages/backend/src/routes/products.ts
- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
fix dishes and resto creation 
adjust buttons in profile section
5. Run tests
> [BE] [FIX] fix dishes and resto creation

- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
Hiding empty categories is broken due to merge conflict. Fixed in this PR.
5. Run tests
> [FE] [FIX] empty category due to merge conflict

- packages/visitorWeb/src/components/RestoCard/RestoCard.tsx
- packages/visitorWeb/src/components/menu/Dish/Dish.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
update favourite lists on profile page, when removing a favourite object (resto or dish) on that page
5. Run tests
> [FE] [FIX] update favourite lists after an item was removed

- packages/backend/src/controllers/allergenDetectionController.ts
- packages/backend/src/controllers/ingredientsController.ts
- packages/backend/src/routes/ingredients.ts
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/services/ingredientsCalls.ts
Fix error when adding disliked ingredient to DB ('Ingredient not found' button).
5. Run tests
> [FE] [FIX] adding disliked ingredient to db via profile

- packages/backend/src/controllers/favouritesController.ts
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
User can see to what restaurant a favourite dish belongs (in profile page, fav dish tab) with reference to the resto menu. This way, they can direct to the resto menu from the fav dish groups.
5. Run tests
> [FE] [ADD] resto reference for fav dishes in profile

- packages/backend/src/controllers/menuController.ts
fixed an issue where the allergen wasn't correctly detected for the menus. 
E.g: 
user allergen: "milk"
dish allergen: "Milk and milk products (includes lactose)"
would have returned false even though it should have triggered
5. Run tests
> [BE] [FIX] updated allergen detection for menu

- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/RestoCard/RestoCard.tsx
- packages/visitorWeb/src/pages/FeatureRequest/FeatureRequest.tsx
- packages/visitorWeb/src/pages/UserSupport/UserSupportPage.tsx
> [FE] [MODIFY] Change share menu pop-up to a custom dialog

- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/MapPage/MapPage.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
moves the address input for user to filter and enables range filter when user has entered their location
5. Run tests
> [FE] [FIX] Fix range filter

- packages/restoWeb/src/pages/ResetPasswordPage/ResetPassword.module.scss
- packages/restoWeb/src/pages/ResetPasswordPage/ResetPassword.tsx
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/ResetPasswordPage/ResetPassword.module.scss
- packages/visitorWeb/src/pages/ResetPasswordPage/ResetPassword.tsx
Inputsfield from the forgot pw page are now wider and also make a safty call for the filter, to not get a error
> [FE] [MODIFY] change styling of the forgot pw page

- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
Fixed consitstency in the styling of the resto Account Page
> [FE] [MODIFY] Styling Account Page

- packages/backend/src/routes/dishes.ts
Removed validation of ingredient (API changed)
If we used unknown ingredient, the api returned an empty ingredient. They changed this behaviour --> we also need to adjust
we now can add dishes, even if the api return nothing
5. Run tests
> [BE] [FIX] create dish even if ingred not found

- packages/backend/src/controllers/ingredientsController.ts
- packages/backend/src/controllers/menuController.ts
- packages/backend/src/middleware/newFilterMiddleware.ts
- packages/visitorWeb/src/pages/MapPage/MapPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
When user has allergens saved in their account the filter will automatically apply these allergens and hide restaurants that don't fit,
5. Run tests
> [FE] [FIX] Fix resto allergen

- packages/restoWeb/package.json
- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
- packages/restoWeb/src/services/restoCalls.ts
- packages/visitorWeb/src/components/RestoCard/Rating/Rating.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/pages/ViewRatingPage/ViewRatingPage.module.scss
- packages/visitorWeb/src/pages/ViewRatingPage/ViewRatingPage.tsx
- packages/visitorWeb/src/pages/ViewRatingPage/index.ts
- packages/visitorWeb/src/router/Router.tsx
> Back log nov alban

- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
fixes an issue where the user allergens where not applied on the filter
5. Run tests
> [FE] [FIX] apply user allergens on filter

- packages/visitorWeb/src/components/CookieBanner/CookieBanner.tsx
- packages/visitorWeb/src/components/Map/Map.module.scss
- packages/visitorWeb/src/components/Map/Map.tsx
- packages/visitorWeb/src/components/RestoDetailOverlay/RestoDetailOverlay.module.scss
- packages/visitorWeb/src/components/RestoDetailOverlay/RestoDetailOverlay.tsx
- packages/visitorWeb/src/pages/IntroPage/IntroPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.module.scss
- packages/visitorWeb/src/router/Router.tsx
Apply fixes for the Visitor Web.
Currently:
- Cookiebanner
- Map Details View (Styling and Logic)
- Restaurant Detail view (Styling and Menu Call)
- MyAccount Page Styling
- Refresher for the Intro Page
> [FE [MODIFY] Cookiebanner fix

- packages/backend/src/routes/categories.ts
change logic how we fetch/send categories (filter) to frontend 
We only want to show categories with products init 
Doesnt make sense to show empty categories
5. Run tests
> [BE] [FIX] only send categories with at least one dish back

- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
> [FE] [FIX] negative price

- packages/restoWeb/src/components/menu/Dish/Dish.tsx
… deleted
Fix the issue explained bellow
1. add Dish to combination
2. delete the dish you added as combination
Expected: dish will be deleted and the main dish wont show anything
Actual: Dish is deleted but main Dish shows empty recomendation.
5. Run tests
> [FE] [FIX] Fix combo staying in place after deletion of dish

- packages/backend/src/routes/login.ts
add check to ensure user will receive a mail in his selected langauge, if no Langauge selected --> use english as default 
User wont received a mail if he doesnt select a language
We always want to send a mail 
5. Run tests
> [BE] [FIX] ensure 2 factor login is working

- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
Fix issue explain bellow 
Where categories where not display when trying to update a dish
1. Have at least 2 categories
2. Go to edit screen of a dish
3. Click on category field
Expected: show list of available categories
Actual: doesnt show any list results
5. Run tests
> [FE] [FIX] Fix issue where categorie where not display when editing

- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
> [FE] [FIX] save menu design id on resto

- packages/backend/src/controllers/restaurantController.ts
- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/restoWeb/src/router/Router.tsx
- packages/shared/models/restaurantInterfaces.ts
- packages/visitorWeb/src/router/Router.tsx
Bugs:
- delete Account and handle redirect to login
- cant register bug
- create resto with restochain dont save the restochain
> [BE] [MODIFY] router logic and resto chains

- packages/backend/src/controllers/restaurantController.ts
> [FE] [FIX] default values in forms

- packages/shared/components/menu/AllergenTags/AllergenTags.tsx
- packages/visitorWeb/i18n/de.json
- packages/visitorWeb/i18n/en.json
- packages/visitorWeb/i18n/fr.json
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/router/Router.tsx
Bugfixed:
- allergene translation (filter, account, menu)
- register route
- delete account -> login screen
> [FE] [MODIFY] Allergene view and router logic

- packages/backend/src/routes/review.ts
- packages/restoWeb/src/pages/MenuPage/MenuPage.module.scss
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
- packages/restoWeb/src/services/qrcodeCall.ts
- packages/visitorWeb/src/pages/Payments/PaymentsPage/PaymentPage.tsx
- packages/visitorWeb/src/pages/RatingPage/RatingPage.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
- packages/visitorWeb/src/pages/ViewRatingPage/ViewRatingPage.tsx
> Latest bugs/alban Web resto en visitor

- packages/backend/src/controllers/mapController.ts
- packages/backend/src/models/userInterface.ts
- packages/backend/src/routes/map.ts
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
- packages/visitorWeb/src/services/mapCalls.ts
when saving a filter, user position will be saved as well and when we load a saved filter user position will be shown
5. Run tests
> [BE] [FIX] fix save/load range filter

- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
> [FE] [FIX] show menu designs

- packages/backend/src/controllers/restaurantController.ts
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
BE: update resto rating when review is added or removed
FE: rating updates with one click 
5. Run tests
> [FE] [FIX] Fix visitor rating

- packages/restoWeb/src/components/dumpComponents/popup/Popup.tsx
- packages/restoWeb/src/pages/AddRestoChainPage/AddRestoChainPage.tsx
> [FE] [ADD] ask for delete confirmation resto chains

- packages/backend/src/routes/images.ts
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/services/imageCalls.ts
fixes an issue where the profile picture gets deleted when user changes an image
5. Run tests
> [BE] [FIX] fixed deletion of profile pic when changing pic

- packages/visitorWeb/src/components/Map/Map.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
fixed runtime error when clicking on the blue dot
when adding/removing the user position from filter filter updates now
5. Run tests
> [FE] [FIX] Fix visitor map filter update

- packages/restoWeb/src/pages/AddCategoryPage/AddCategoryPage.tsx
- packages/restoWeb/src/pages/AddRestoChainPage/AddRestoChainPage.tsx
Before, always deleted last element in list instead of the one with correct index.
5. Run tests
> [FE] [FIX] delete resto chain

- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/routes/payments.ts
- we now use userResto db to store paymentinfos for restoUser
-
- bugfix --> we now can add/delete restopayments and userpayments
5. Run tests
> [BE] [FIX] use restoUser db for restoUser payment

- packages/backend/src/controllers/allergenDetectionController.ts
- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/routes/dishes.ts
- packages/backend/src/routes/ingredients.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/menu/Dish/Dish.tsx
- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
- packages/restoWeb/src/pages/UserInsights/UserInsights.tsx
Detecting allergens automaticly now for dishes and enabled allergens translation
> Resto page fix allergens gylian

- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/controllers/restaurantFilterController.ts
- packages/backend/src/middleware/newFilterMiddleware.ts
- packages/backend/src/models/communicationInterfaces.ts
- packages/backend/src/models/restaurantInterfaces.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/forms/DishForm/DishForm.module.scss
- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
- packages/restoWeb/src/pages/EditDishPage/EditDishPage.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/shared/models/dishInterfaces.ts
> [FE] [FIX] adding and deleting resto chain in dish form

- packages/restoWeb/src/components/menu/Dish/Dish.module.scss
- packages/restoWeb/src/components/menu/Dish/Dish.tsx
- packages/restoWeb/src/pages/AddCategoryPage/AddCategoriyPage.module.scss
- packages/restoWeb/src/pages/DishesPage/DishesPage.module.scss
- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/restoWeb/src/pages/LoginPage/LoginPage.tsx
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/restoWeb/src/pages/ProductsPage/ProductsPage.module.scss
- packages/restoWeb/src/router/Router.tsx
- packages/visitorWeb/src/pages/LoginPage/LoginPage.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
- packages/visitorWeb/src/router/Router.tsx
Bug fixes
1. My Account Page Button styling
2. My Account Page Button Placement
3. Empty Msg for dishes / products / resto styling
4. login edgecase fix
> [FE] [MODIFY] Styling for Account Page

- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
> [FE] [FIX] we now can filter again

- packages/restoWeb/src/router/Router.tsx
- packages/visitorWeb/src/router/Router.tsx
> [FE] [MODIFY] change routing

- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/visitorWeb/src/pages/RestoPage/RestoPage.tsx
> [FE] [FIX] show ads only when free user

- packages/restoWeb/src/router/Router.tsx
- packages/visitorWeb/src/router/Router.tsx
> Routing fix

- packages/visitorWeb/src/components/Map/Map.tsx
> [FE] [FIX] fix runtime error adding removing fav map

- packages/visitorWeb/src/components/RestoCard/RestoCard.tsx
> [FE] [FIX] picture will always load but doesnt caus crashes

- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
> [FE] [ADD] ingredient info note

- packages/restoWeb/src/router/Router.tsx
- packages/visitorWeb/src/router/Router.tsx
> [FE] [FIX] router visitor & resto

- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
> [FE] [FIX] menu designs visitor

- packages/backend/src/controllers/allergenDetectionController.ts
- packages/backend/src/middleware/ingredientsMiddleWare.ts
- packages/backend/src/routes/dishes.ts
> [BE] [FIX] fix allergendetection while creating dish

- packages/backend/src/controllers/allergenDetectionController.ts
- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/middleware/ingredientsMiddleWare.ts
- packages/backend/src/routes/dishes.ts
> [BE] [FIX] fix allergen mapping while dish editing

- packages/visitorWeb/src/components/RestoCard/Rating/Rating.module.scss
> [FE] [MODIFY] fix rating styling in detail popup

- packages/backend/src/controllers/dishesController.ts
- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
- packages/shared/models/restaurantInterfaces.ts
Before: If a dish was added to a new restaurant, the pictureId was not saved and therefore the dish was shown without picture for addional restos.
5. Run tests
> [BE] [MODIFY] pass dish pictureId to additional restos

- packages/backend/src/controllers/allergenDetectionController.ts
- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/ingredientsController.ts
- packages/backend/src/controllers/productsController.ts
- packages/backend/src/routes/dishes.ts
- packages/backend/src/routes/ingredients.ts
- packages/backend/src/routes/products.ts
- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
- packages/restoWeb/src/services/ingredientsCalls.ts
- detect allergens for ingredients
- products use allergens from ingredient list
- dishes use allergens from product list
5. Run tests
> [FE] [MODIFY] show allergen tags on products

- packages/visitorWeb/src/components/Map/Map.tsx
- packages/visitorWeb/src/components/RestoCard/Rating/Rating.tsx
fixes the images for the popup and resto detail and popup shows now correct rating
5. Run tests
> [FE] [FIX] Fix map popup

- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
We can now navigate with the subheaders to our sections
> [FE] [MODIFY] Fancy Menu Design

- packages/restoWeb/src/components/dumpComponents/popup/Popup.module.scss
- packages/restoWeb/src/components/dumpComponents/popup/Popup.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
Deleted Option of having a default menu design
Problem is fixed that we have problems with deleting restos when 2 exists
> [FE] [MODIFY] Default Menu Design + delete resto issue

- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
fixes an error for the resto form where picturesId is missing when saving the object
5. Run tests
> [FE] [FIX] Hotfix resto form

- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/restoWeb/src/router/Router.tsx
- packages/restoWeb/src/services/restoCalls.ts
- packages/visitorWeb/src/components/CookieBanner/CookieBanner.tsx
- packages/visitorWeb/src/components/Filter/Filter.tsx
- packages/visitorWeb/src/router/Router.tsx
- packages/visitorWeb/src/services/categorieCalls.ts
- packages/visitorWeb/src/services/favourites.ts
- packages/visitorWeb/src/services/filterCalls.ts
- packages/visitorWeb/src/services/imageCalls.ts
- packages/visitorWeb/src/services/ingredientsCalls.ts
- packages/visitorWeb/src/services/mapCalls.ts
- packages/visitorWeb/src/services/menuCalls.ts
- packages/visitorWeb/src/services/permissionsCalls.ts
- packages/visitorWeb/src/services/profileCalls.ts
- packages/visitorWeb/src/services/userCalls.ts
when the token expired/was invalid the user was redirected to the login page but was shown runtime errors. these runtime errors are now fixed
5. Run tests
> [FE] [FIX] Fix expired token

- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/models/communicationInterfaces.ts
- packages/backend/src/routes/dishes.ts
- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
- packages/restoWeb/src/services/dishCalls.ts
If dish is registered in several restos, previously it would only update the dish data for the first resto as the dish id is resto specific and not unique. Prevent several dishes with the same name per user to reduce risk of error. 
5. Run tests
> [BE] [FIX] update dish name for several restos

- packages/restoWeb/src/pages/DishComboPage/DishComboPage.tsx
> [FE] [FIX] make dish combo non required

- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/productsController.ts
added funktion to get all restaurants by name but typesave
we now can change products and dishes will update automaticly 
We need to update all dishes if we change a product 
5. Run tests
> [BE] [FIX] update all dishes if products changes

- packages/restoWeb/src/pages/UserSupport/UserSupportPage.tsx
> lastestBugs/Alban: resolved bug q&a

- packages/restoWeb/src/components/menu/Dish/Dish.tsx
> [FE] [FIX] make combos clickable to see allergens

- packages/restoWeb/src/components/forms/DishForm/DishForm.tsx
> [FE] [FIX] only check name if new dish

- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/productsController.ts
- packages/backend/src/models/communicationInterfaces.ts
ensure that we take the correct id of the dish.
add combo to ensure that we dont delete it
we want to be able to remap dishes if allergens change 
need to show all allergens correctly
5. Run tests
> [BE] [FIX] use correct dish object to remapp allergens

- packages/backend/src/controllers/imageController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/middleware/imagesMiddleWare.ts
- packages/backend/src/routes/images.ts
- packages/backend/src/routes/restaurants.ts
- packages/restoWeb/src/components/RestoCard/RestoCard.tsx
- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
- packages/restoWeb/src/pages/EditRestaurantPage/EditRestaurantPage.tsx
- packages/restoWeb/src/pages/MenuPage/MenuPage.tsx
- packages/restoWeb/src/services/callImages.ts
- packages/restoWeb/src/services/restoCalls.ts
change routes to delete, change and get restaurants only by id
ensure that we delete,get and edit  the correct restaurant
In the past it happens, if we have two restaurants with the same name, it deleted always the first one.
now it deletes the correct one
Same for getting and editing 
5. Run tests
> [BE] [FIX] only use id for restaurants 

- packages/backend/src/controllers/dishesController.ts
- packages/restoWeb/src/components/menu/Dish/Dish.tsx
- packages/visitorWeb/src/components/menu/Dish/Dish.tsx
Deletes reference to deleted combo dishes in DB. Assure correct displaying of combo banner in FE.
5. Run tests
> [BE] [MODIFY] remove combos on dish delete

- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
- packages/restoWeb/src/components/forms/RestaurantForm/RestaurantForm.tsx
- packages/restoWeb/src/pages/AddCategoryPage/AddCategoryPage.tsx
- packages/restoWeb/src/pages/DishComboPage/DishComboPage.tsx
- packages/restoWeb/src/services/dishCalls.ts
Dont allow objects with same name per user: restaurants, categories (per resto, not user), products,
Also, load dishes per user for combo options instead of load dishes per one resto (as we can assign dishes to several resto, it resulted in an incomplete selection).
5. Run tests
> [FE] [MODIFY] prevent objects with same name per user

- packages/visitorWeb/src/components/RestoCard/RestoCard.tsx
- packages/visitorWeb/src/pages/MenuPage/MenuPage.tsx
- packages/visitorWeb/src/services/menuCalls.ts
now applies the correct menu design when the menu is shared
5. Run tests
> [FE] [FIX] fix missing menu design when shared

- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
Dont show duplicate ingredients in the product form.
5. Run tests
> [FE] [MODIFY] hide duplicate ingredients

- packages/backend/src/controllers/dishesController.ts
- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/routes/dishes.ts
- packages/backend/src/routes/ingredients.ts
- packages/backend/src/routes/products.ts
- packages/restoWeb/src/components/menu/Dish/Dish.tsx
- packages/restoWeb/src/pages/DishesPage/DishesPage.tsx
In case there are several restos with same name, ensure its assigned to correct user (several restos with same name are not allowed per user as of https://github.com/GuardosEpitech/Guardos/pull/267).
Fix BE error when editing dishes.
5. Run tests
> [BE] [MODIFY] fix editing and assigning of products

- packages/restoWeb/src/pages/DiscountDishPage/DiscountDishPage.tsx
> [FE] [FIX] Fix dish discount

- packages/restoWeb/i18n/de.json
- packages/restoWeb/i18n/en.json
- packages/restoWeb/i18n/fr.json
> [FE] [FIX] removed {{ email }} from error message

- packages/visitorWeb/src/components/Header/Header.tsx
- packages/visitorWeb/src/pages/LoginPage/LoginPage.tsx
- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/router/Router.tsx
Solved every Routing Problem for Visitor
> [FE] [MODIFY] Routing Logic

- packages/restoWeb/src/components/dumpComponents/Header/Header.tsx
- packages/restoWeb/src/pages/AppOutlet/AppOutlet.module.scss
- packages/restoWeb/src/pages/HomePage/HomePage.tsx
- packages/restoWeb/src/pages/LoginPage/LoginPage.tsx
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.module.scss
- packages/restoWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/restoWeb/src/router/Router.tsx
All of my Tickets for resto web werde finished here
> [FE] [MODIFY] Change Router Logic and fix Profil Page styling

- packages/restoWeb/src/components/RestoCard/RestoCard.tsx
Opening Day/Hour are now display in the right order even if some day are closed 
5. Run tests
> [FE][FIX] Fix issue with OpeningHours that where displaying with wrong days

- packages/backend/src/controllers/restaurantController.ts
- packages/backend/src/routes/restaurants.ts
- packages/restoWeb/src/pages/AddCategoryPage/AddCategoryPage.tsx
- packages/shared/models/categoryInterfaces.ts
- packages/shared/models/dishInterfaces.ts
when editing a category the dishes from the old category get mapped to the new category
5. Run tests
> [FE] [FIX] fix edit category

- packages/backend/src/controllers/favouritesController.ts
when resto that was liked gets deleted
you get runtime errors in profile for 'favourite Restaurants' panel (other cases like for dishes and reviews works fine)
if you have one dish liked that is deleted, every get dish and restaurant call will fail and get you runtime error
5. Run tests
> [BE] [MODIFY] only return valid favs

- packages/backend/src/controllers/productsController.ts
- packages/backend/src/routes/products.ts
- packages/restoWeb/src/components/forms/ProductForm/ProductForm.tsx
the check is now normalising the name to identify if the product was already added
5. Run tests
> [BE] [FIX] when adding prod with same name

- packages/visitorWeb/src/pages/MyAccountPage/MyAccountPage.tsx
- packages/visitorWeb/src/router/Router.tsx
Task in here completed:
1. Click on Welcome to guardos redirected to login page on "restoWeb"
2. Delete Account -> does not redirect to login page
3. When you save in the profile you get redirected to the home page
> [FE] [MODIFY] fix Routing logic
